on: [push, pull_request]
name: iOS
jobs:
  Integration:
    name: "Integration (${{ matrix.runs_on }}, ${{ matrix.python }})"
    defaults:
      run:
        shell: ${{ matrix.run_wrapper || 'bash --noprofile --norc -eo pipefail {0}' }}
    runs-on: ${{ matrix.runs_on || 'macos-latest' }}
    strategy:
      matrix:
        include:
          - runs_on: macos-latest
            python: '3.9'
          - runs_on: apple-silicon-m1
            run_wrapper: arch -arm64 bash --noprofile --norc -eo pipefail {0}
            python: '3.9.7'
    steps:
    - name: Setup python
      # Needs to be skipped on our self-hosted runners tagged as 'apple-silicon-m1'
      if: ${{ matrix.runs_on  != 'apple-silicon-m1' }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - uses: actions/checkout@v2
    - name: Setup environment
      run: |
        source .ci/osx_ci.sh
        arm64_set_path_and_python_version ${{ matrix.python }}
        pip install -e .
        pip install Cython cookiecutter pbxproj
    - name: Check buildozer installation
      run: |
        source .ci/osx_ci.sh
        arm64_set_path_and_python_version ${{ matrix.python }}
        buildozer --help
    - name: Initialize buildozer in project folder
      run: |
        source .ci/osx_ci.sh
        arm64_set_path_and_python_version ${{ matrix.python }}
        buildozer init
    - name: Install dependencies
      run: |
        source .ci/osx_ci.sh
        arm64_set_path_and_python_version ${{ matrix.python }}
        brew install autoconf automake libtool pkg-config
    - name: buildozer ios debug
      run: |
        source .ci/osx_ci.sh
        arm64_set_path_and_python_version ${{ matrix.python }}
        touch main.py
        buildozer ios debug
