on: [push, pull_request]
name: Tests
jobs:
  Tests:
    name: base
    strategy:
      matrix:
        python:
           - '3.8'
           - '3.9'
           - '3.10'
           - '3.11'
        os:
          - 'ubuntu-latest'
          - 'macOs-latest'
        architecture:
          - 'x64'

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

    - name: Requirements
      run: |
        pip install -U coveralls setuptools tox>=2.0
    - name: Tox
      run: tox
    - name: Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_SERVICE_NAME: github
      run: coveralls

  Docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Docker build
      run: docker build --tag=kivy/buildozer .
    - name: Docker run
      run: docker run kivy/buildozer --version

  Documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Requirements
      run: pip install -U sphinx
    - name: Check links
      run: sphinx-build -b linkcheck docs/source docs/build
    - name: Generate documentation
      run: sphinx-build docs/source docs/build

